### ISSUE TITLE
Logo/Icon Design

### ISSUE THREAD

**Issue by zularizal** [dhsavell/ajo#1]
Hi @dhsavell , I'm a graphic designer, after I review your project, I'm interested in your project and I want to contribute by creating a logo/icon for your project. What do you think?

**Comment by zularizal** [comment]
Okay. Give me time to make it. I will upload the logo proposal in the next reply.

**Comment by zularizal** [comment]
Sorry for late reply. This is the logo that I have designed for your project. This logo is in the form of a pencil which is composed of ajo and it is related to the journal. I make it in a simple style and can be used in one color.

If something wants to be changed, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/47610515-4d75c400-da81-11e8-9ad5-02bc2903554a.png)

**Comment by dhsavell** [comment]
Awesome! I'm a fan of the pencil symbol and the overall concept of the logo. My only concern is how the logo would look at smaller sizes, but I suppose I'll have to test this out myself soon and get back to you (I have a feeling it will be alright, but I just want to check). 

For now, would you mind uploading the monochrome and blue gradient icons (no background) as SVG files? Thank you very much for you work!

**Comment by zularizal** [comment]
Sorry for late respond
Check this, I have uploaded it to drive

https://drive.google.com/open?id=1fjTK43v4tWBtIoqH9nsvzjfcldS7X3pr
